### ISSUE TITLE
Third Party Libraries 'export' error.

### ISSUE THREAD

**Issue by merihs** [patrickmichalina/fusebox-angular-universal-starter#131]
I added 'ngx-bootstrap' library to my project but it throws 'SyntaxError: Unexpected token export' error.
How do we add third party libraries.

```
C:\Development\Workspaces\TESTS\cm-web-fusebox\node_modules\ngx-bootstrap\modal\index.js:1
(function (exports, require, module, __filename, __dirname) { export { ModalContainerComponent } from './modal-container.component';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at u (C:\Development\Workspaces\TESTS\cm-web-fusebox\dist\server.js:2339:1092)
```

**Comment by patrickmichalina** [comment]
Please check out this hastily made diff:

https://github.com/patrickmichalina/fusebox-angular-universal-starter/compare/bootstrap

Be sure to remove the material design references as well if you only want bootstrap.

<img width="1147" alt="screen shot 2017-09-04 at 9 58 25 am" src="https://user-images.githubusercontent.com/6701211/30031607-d2ccde96-9157-11e7-96c9-e094608b46d3.png">
